{"uuid": "45c7e488-e8d1-4c14-8e61-6d98b7492d91", "children": ["a6b32dba-3d7c-4073-ab2a-b8b959dd1477"], "befores": [{"name": "auth_default_user", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=56634): Read timed out. (read timeout=120)\n", "trace": "  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\conftest.py\", line 32, in auth_default_user\n    account.open(urls.LOGIN_URL)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\pages\\base_page.py\", line 17, in open\n    self.driver.get(url)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\util\\util.py\", line 39, in reraise\n    raise value\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 536, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 367, in _raise_timeout\n    raise ReadTimeoutError(\n"}, "steps": [{"name": "Открываем страницу: 'https://stellarburgers.nomoreparties.site/login'", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=56634): Read timed out. (read timeout=120)\n", "trace": "  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\pages\\base_page.py\", line 17, in open\n    self.driver.get(url)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\util\\util.py\", line 39, in reraise\n    raise value\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 536, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"D:\\Development\\Diplom_Roman_Makarenkov_18\\Diplom_3\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 367, in _raise_timeout\n    raise ReadTimeoutError(\n"}, "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/login'"}], "start": 1744228321948, "stop": 1744228441956}], "start": 1744228321948, "stop": 1744228441959}], "start": 1744228321948, "stop": 1744228446107}